services:
  next:
    hostname: next.local
    build:
      dockerfile: ./infra/next/Dockerfile
      context: .
    volumes:
      - ./next:/next
      - /next/node_modules
    ports:
      - "3000:3000"
    networks:
      - quotter
    environment:
      - CHOKIDAR_USEPOLLING=true

  php:
    hostname: php.local
    build:
      dockerfile: ./infra/php/Dockerfile
      context: .
    volumes:
      - ./src:/var/www/html
    networks:
      - quotter
    command: >
      sh -c "php artisan storage:link && php-fpm"

  web:
    hostname: web.local
    build:
      dockerfile: ./infra/web/Dockerfile
      context: .
    ports:
      - 80:3030
      - 8080:9090
    volumes:
      - ./src/public:/var/www/html/public
      - ./src/storage:/var/www/html/public/storage
      - ./infra/web/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - quotter
    depends_on:
      - php
      - next

  db:
    image: "mysql/mysql-server:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravel
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - quotter

volumes:
  data:

networks:
  quotter:
    driver: bridge
